config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get 'welcome/index'
  get 'users/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :articles do
    resources :comments
  end
  
  root 'welcome#index'

end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :taggings, dependent: :destroy
    has_many :tags, through: :taggings

    validates :title, 
    presence: true, 
    length: { minimum: 5 }

    def all_tags=(names)
        self.tags = names.split(",").map do |name|
            Tag.where(name: name.strip).first_or_create!
        end
    end
    
    def all_tags
        self.tags.map(&:name)
    end

    def self.tagged_with(name)
        Tag.find_by_name!(name).posts
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

    def index
        @articles = Article.all.reverse
    end

    def new
        @article = current_user.articles.build        
    end

    def edit
        @article = Article.find(params[:id])
    end

    def create
        @article = current_user.articles.build(article_params)
        if @article.save
            redirect_to @article
        else 
            render 'new'
        end
        
    end

    def show
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
    
        if @article.update(article_params)
            redirect_to @article
        else
            render 'edit'
        end
    end


    def destroy
        @article = Article.find(params[:id])
        if @article.destroy
            redirect_to articles_path
        else
            redirect_to(@article)
        end
    end

    private

    def article_params
        params.require(:article).permit(:title, :text, current_user.id, :all_tags)
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for @article, html: {class: 'form-horizontal'}, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> 
        prohibited this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <%= form.input :title %>
  <%= form.input :text, input_html: { row: 12 } %>
  <%= form.input :all_tags, placeholder: "Tags separated with comma" %>

  <%= form.button :submit, class: "btn-primary" %>
 
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>
 
<%= render 'form' %> 
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
  <h2 class="mt-2">Listing Articles</h2> 
    
  <% @articles.each do |article| %>
    <div class="mb-3 border rounded my-3">
    
          <div class="text-dark bg-light p-1">
              <p class="pt-2 ml-2 text-capitalize "> <%= link_to article.title, article_path(article) %> </p>
          </div>

          <div class="container">
              <div class="p-1" style="width: 90%">
                <%= article.text.truncate(280) %>
              </div>
              
              <% article.all_tags.each do |tag| %>
                <div class="my-3 badge badge-info" style="font-size: 80%"> <%= tag %></div>    
              <% end %>
                           
              <div class="text-muted" style="text-size: 50%">
                <%= article.user.email %> | 
                <%= article.created_at.strftime("%b %d - %y") %> | 
                <%= article.created_at.strftime("%k:%M") %> 
              </div>

              <div class="mb-2" >
                <% if article.user == current_user %>
                  <button class="btn-info rounded" ><%= link_to 'Edit', edit_article_path(article),style: 'color:#FFFFFF;', class: 'css_class' %></button>
                  <button class="btn-danger rounded"><%= link_to 'Destroy', article_path(article), method: :delete, 
                      data: { confirm: 'Are you sure?' }, style: 'color:#FFFFFF;', class: 'css_class' 
                  %></button>
                <% end %>
              </div>

          </div>
          
    </div>
  <% end %> 
</div>

app/views/articles/new.html.erb
<div class="container p-2">
    <h3>Create Article</h3>

    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div class="container my-4" style="width: 80%"> 
    <div class="p-2 ">
      <div class="p-1 border-bottom" style="font-size: 220%; width: 90%; margin: auto"> <%= @article.title %></div>
      <div class="my-2 text-justify" style="font-size: 100%; width: 80%; margin: auto"> <%= simple_format(@article.text) %></div>
      
      <% @article.all_tags.each do |tag| %>
        <div class="my-3 badge badge-info" style="font-size: 80%"> <%= tag %></div>    
      <% end %>  
      
      <div class="text-muted" style="">Author: <%= @article.user.email %></div>
    </div>
    
    <div class=" p-2 border-bottom">
    <% if @article.user == current_user %>
      <%= link_to 'Edit', edit_article_path(@article) %> | 
      <%= link_to 'Delete', article_path(@article), method: :delete, 
          data: { confirm: 'Are you sure?' } 
      %>
    <% end %>
    </div>

    <div class="container border-bottom">  
      <div class=""> <h3>Comments</h3></div>
      <div class=""> <%= render @article.comments %></div>
    </div>

    <div class="container-fluid" style=""><%= render 'comments/form' %></div>
    
</div>

app/views/articles/temp.index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Vector Blog</title>
    <!-- Bootstrap core CSS -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:400,300,500,600,700,800,900' rel='stylesheet' type='text/css'>
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/icon-component.css" rel="stylesheet">
    <link href="css/font-awesome.css" rel="stylesheet">

    <link href="css/blog.css" rel="stylesheet">


</head>
<body class="no-intro-img">
<div class="body-wrapper">
    <!-- /.navbar -->
    <div class="light-wrapper page-title">
        <div class="container inner">
            <div class="pull-left logo-width">
                <img class="vector-logo" src="img/logo.png" alt="Vector Logo Here">
            </div>
        </div>
        <!-- /.container -->
    </div>
    <!-- /.page-title -->
    <div class="dark-wrapper">
        <div class="container inner">
            <div class="blog grid-view-img">
                <div class="blog-posts">
                    <div class="isotope">
                        <!-- /.post-grid -->
                        <% @articles.each do |article| %>
                        <div class="post-grid">
                            <div class="post wow fadeIn" data-wow-duration="1s" data-wow-delay="2.7s">
                                <div class="content">
                                    <div class="meta"><%= article.created_at %><span class="category"></span></div>
                                    <h2 class="post-title"><a><%= link_to article.title, article_path(article) %></a></h2>
                                </div>
                                <!-- /.content -->
                            </div>
                            <!-- /.post -->
                        </div>
                        <% end %> 
                        <!-- /.post-grid -->
                    </div>
                    <!-- /.isotope -->
                </div>
                <!-- /.blog-posts -->
            </div>
            <!-- /.blog -->
        </div>
        <!--/.container -->
    </div>
    <!--/.dark-wrapper -->



</div>
<!--/.body-wrapper -->
<script src="js/jquery.js"></script>
<script src="js/bootstrap.min.js"></script>
<script src="js/plugins.js"></script>
<script src="js/scripts.js"></script>
<!-- DEMO ONLY -->

<!--<script type="text/javascript" src="switcher/switchstylesheet.js"></script>-->
<script type="text/javascript">
    $(document).ready(function(){
        $(".changecolor").switchstylesheet( { seperator:"color"} );
    });
</script>
</body>
</html>